### PR TITLE
Protect against weird bounds combinations

### LINKED ISSUE #21: Probable bugs / incorrect behaviour
Listing these off the top of my head as things that aren't implemented correctly:

- adding different bounds:
  - [x] confirmed
  - [ ] fixed
  - [ ] tests
```julia
x = addvariable!(m)
c = addconstraint!(m, SingleVariable(m), LessThan(1.0))
addconstraint!(m, SingleVariable(m), LessThan(0.0))  # this should error
# instead
modify!(m, c, LessThan(0.0))
```

- adding different variable types:
  - [x] confirmed
  - [ ] fixed
  - [ ] tests
```julia
x = addvariable!(m)
c = addconstraint!(m, SingleVariable(m), ZeroOne())
addconstraint!(m, SingleVariable(m), Semiinteger(2,4))  # this should error
# instead
transform!(m, c, Semiinteger(2,4))
```

### PR DESCRIPTION
**Pull request by joaquimg**
Fixes #21

There are a few test fails, two main kinds:

1) adding multiple constraints of the same type, which will be blocked by this.

2) ordered indices, we could add a version fo that ignoring SingleVariable constraints
For all the linquad solvers these constraints are special...

### CODE REVIEW

File: src/constraints/singlevariable.jl [hunk 1]
```diff
@@ -40,11 +40,30 @@ function setvariablebound!(m::LinQuadOptimizer, v::SinVar, set::IV)
...
 # add constraint
 function MOI.addconstraint!(m::LinQuadOptimizer, v::SinVar, set::S) where S <: LinSets
+    checkexisting(m, v, set)
+    checkconflicting(m, v, set, MOI.Semicontinuous(0.0, 0.0))
+    checkconflicting(m, v, set, MOI.Semiinteger(0.0, 0.0))
+    checkconflicting(m, v, set, MOI.ZeroOne())
     setvariablebound!(m, v, set)
-    m.last_constraint_reference += 1
-    ref = SVCI{S}(m.last_constraint_reference)
+    ref = SVCI(v, set)
```
Comment (odow) [inline src/constraints/singlevariable.jl]: Does this impact the requirement to return constraints in the order that they were created?
https://github.com/JuliaOpt/LinQuadOptInterface.jl/blob/11fb079aa1a3b63a21f49141671ee1b5aa0392e8/src/constraints.jl#L85

Comment (joaquimg) [reply src/constraints/singlevariable.jl]: Yes it does.
I am proposing that this rule is not applied to Single variable constraints since we only have one of each - since they are tied to the variable reference they will be unique...

Comment (joaquimg) [reply src/constraints/singlevariable.jl]: the well ordering on variables will keep these in some fixed order

Comment (mlubin) [reply src/constraints/singlevariable.jl]: I see the issue with http://www.juliaopt.org/MathOptInterface.jl/latest/apireference.html#MathOptInterface.ListOfConstraintIndices. We definitely want the constraint indices to be tied to the variable indices for bound-type constraints. On the other hand, we should be consistent with how constraints work across all classes of constraints. What about using an `OrderedSet` to maintain the list of constraints in the order they're added?
